/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudiesRouteImport } from './routes/studies'
import { Route as ProtocolSearchRouteImport } from './routes/protocol-search'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ConfigureRouteImport } from './routes/configure'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudiesStudyIdRouteImport } from './routes/studies_.$studyId'

const StudiesRoute = StudiesRouteImport.update({
  id: '/studies',
  path: '/studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolSearchRoute = ProtocolSearchRouteImport.update({
  id: '/protocol-search',
  path: '/protocol-search',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRoute = ConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiesStudyIdRoute = StudiesStudyIdRouteImport.update({
  id: '/studies_/$studyId',
  path: '/studies/$studyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configure': typeof ConfigureRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/protocol-search': typeof ProtocolSearchRoute
  '/studies': typeof StudiesRoute
  '/studies/$studyId': typeof StudiesStudyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configure': typeof ConfigureRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/protocol-search': typeof ProtocolSearchRoute
  '/studies': typeof StudiesRoute
  '/studies/$studyId': typeof StudiesStudyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configure': typeof ConfigureRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/protocol-search': typeof ProtocolSearchRoute
  '/studies': typeof StudiesRoute
  '/studies_/$studyId': typeof StudiesStudyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configure'
    | '/home'
    | '/login'
    | '/portfolio'
    | '/protocol-search'
    | '/studies'
    | '/studies/$studyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configure'
    | '/home'
    | '/login'
    | '/portfolio'
    | '/protocol-search'
    | '/studies'
    | '/studies/$studyId'
  id:
    | '__root__'
    | '/'
    | '/configure'
    | '/home'
    | '/login'
    | '/portfolio'
    | '/protocol-search'
    | '/studies'
    | '/studies_/$studyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigureRoute: typeof ConfigureRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRoute
  ProtocolSearchRoute: typeof ProtocolSearchRoute
  StudiesRoute: typeof StudiesRoute
  StudiesStudyIdRoute: typeof StudiesStudyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studies': {
      id: '/studies'
      path: '/studies'
      fullPath: '/studies'
      preLoaderRoute: typeof StudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol-search': {
      id: '/protocol-search'
      path: '/protocol-search'
      fullPath: '/protocol-search'
      preLoaderRoute: typeof ProtocolSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studies_/$studyId': {
      id: '/studies_/$studyId'
      path: '/studies/$studyId'
      fullPath: '/studies/$studyId'
      preLoaderRoute: typeof StudiesStudyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigureRoute: ConfigureRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRoute,
  ProtocolSearchRoute: ProtocolSearchRoute,
  StudiesRoute: StudiesRoute,
  StudiesStudyIdRoute: StudiesStudyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
